### ISSUE TITLE
IMPORTANT

### ISSUE THREAD

**Issue by leo** [now/ned#1]
Hey!

Leo from [ZEIT](http://zeit.co) here.

I wrote you an email, but it seems like it didn't reach you. Would you mind messaging me at leo@zeit.co?

Thank you!

**Comment by luciusmagn** [comment]
Didn't expect ZEIT here, love your work.

Let me guess, you want to trade for his username because it would be useful for <https://zeit.co/now>, right?

Good luck

**Comment by now** [comment]
#WONTFIX
